### ISSUE TITLE
Exported trait loses type information

### ISSUE THREAD

**Issue by wheaties** [milessabin/export-hook#15]
The following code:

``` scala
import export._

trait Foo[A]{
    type Out
    def value: Out
}

object Foo extends LowFoo

@imports[Foo]
trait LowFoo

trait Bar[A] extends Foo[A]

@exports
object Bar{
    type Aux[A, B] = Bar[A]{ type Out = B }
    implicit def yo[Int]: Aux[Int, Double] = new Bar[Int]{
        type Out = Double
        def value = 2.0
    }
}

object Yo{
    import Bar.exports._

    def same[A](x: A, y: A): Unit = {}

    def dot[A](x: A)(implicit b: Foo[A]): b.Out = b.value

    same[Double](2.0, dot(1))
}
```

will cause

```
[error] /Users/oreese/Workspace/playground/Foo.scala:33: type mismatch;
[error]  found   : Bar[Int]#Out
[error]  required: Double
[error]     same[Double](2.0, dot(1))
[error]                          ^
[error] one error found
[error] (main/compile:compileIncremental) Compilation failed
```

The error goes away if the implicit is a `Bar` in the `dot` function.

**Comment by milessabin** [comment]
Looking closely, it seems that it simply isn't going to be possible to preserve the refinements when using the en-masse form of export ... at the level of the object as a whole all we know about is the type constructor `Bar` and there's no obvious way to infer the form of any refinements of `Bar` which might be used in implicit definitions.

It's not all bad news, however, because it turns out that the method level annotation does the right thing, so if you add `@export` to `implicit def yo` the examples compiles as expected.

**Comment by wheaties** [comment]
I'm getting an `unexpected tree shape` error by doing that. I'll open a new ticket as per your request.

**Comment by wheaties** [comment]
You can close this as importing the specific object will in fact preserve the type level information. Reexport will not work, so I need to figure out a way around that.

**Comment by milessabin** [comment]
Thanks for the update.
